name: Continuous Integration

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the development branch
  push:
    branches:
      - development

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "createPullRequest"
  createPullRequest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      # Runs the GitHub Actions created by Peter Evans to create a pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Merge dev branch into main
          title: 'Merge "development" branch into main'
          body: >
            This PR is auto-generated by 
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
          branch: development
          base: main
          labels: automated pr
